### ISSUE TITLE
Error: Evaluation failed: ReferenceError: getInfo is not defined

### ISSUE THREAD

**Issue by redone147** [dtinth/html5-animation-video-renderer#13]
Hi,

I tried this program, but I encountered this problem "getInfo is not defined", is there a solution for it?

**Comment by dtinth** [comment]
@redone147 Your animation page is missing `getInfo()` function. You must define it in your page. [Please check out the docs for more details](https://github.com/dtinth/html5-animation-video-renderer#creating-your-html5-animation).
