### ISSUE TITLE
Migrate CI pipeline from CircleCI to GitHub Actions

### ISSUE THREAD

**Issue by dtinth** [dtinth/html5-animation-video-renderer#14]
## Background

I would like to consolidate the project and build pipeline on GitHub.

## Task

- Create a GitHub Actions workflow based on [CircleCI Config](https://github.com/dtinth/html5-animation-video-renderer/blob/master/.circleci/config.yml)
- Currently the CircleCI pipeline is failing due to it using an outdated operating system. For GitHub Actions, please make it run on latest Ubuntu.
- Your PR should:
   - Contain a new workflow file, e.g. `.github/workflows/ci.yml` that implements the same testing as CircleCI.
   - The pipeline should run successfully, generating videos and image files in the output folder, which is then [uploaded as a build artifact](https://github.com/actions/upload-artifact).
   - The original CircleCI config should be replaced with [a dummy config](https://notes.dt.in.th/CircleCIDummyConfig).
- Please include a screenshot of GitHub Actions running successfully in the PR to confirm that it is working.

## Hacktoberfest

If you would like to work on this task, please write a comment stating your intent. We will then assign the issue to you. To ensure continuity, the issue will be unassigned after 3 days of inactivity — so please keep us updated.

**Comment by oktak** [comment]
I would like to take this for Hacktoberfest. May I?

**Comment by dtinth** [comment]
Fixed by @oktak in #15.
