### ISSUE TITLE
Open functions to run rendering inside own app

### ISSUE THREAD

**Issue by Aliaksandr-Kasko-JazzTeam** [dtinth/html5-animation-video-renderer#7]
Hello.
Could you please open functions to be able to use your library inside other Node.js app?
Something like this:
```
const renderer = require('html5-animation-video-renderer');
// ...
const options = {
    // ...
};
const video = renderer.render(file, options);
```

**Comment by dtinth** [comment]
@Aliaksandr-Kasko-JazzTeam Hello, thanks for the suggestion!

Currently I have no plan to make this project into a library. However it is opensource, please feel free to fork and publish a library based on the code you found here.
